Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-trusty-for-ci"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.provision "shell", inline: "su vagrant -c /vagrant/inside_vagrant.sh | tee /vagrant/console.log"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
  end
end
